### PR TITLE
New worker architecture

### PR DESCRIPTION
**Pull request by corvus-ch**
Added package structure and interface for new architecture supporting several
implementations for calling worker scripts.

### CODE REVIEW

**Comment by corvus-ch** [comment]
@johnduro I have created an interface intended to support different ways to execute worker scripts. Do you thing you can work with that for #65. Please also have a look at https://github.com/corvus-ch/rabbitmq-cli-consumer/wiki/Architecture.

**Comment by johnduro** [comment]
@corvus-ch I looked at the architecture and i think i can work with it. I have to take a little time to discover the interfaces in go.

How do you think we should do ? You merge the interface + the exec worker refactored and then i'll implement the fast-cgi one ?

**Comment by corvus-ch** [comment]
> How do you think we should do ? You merge the interface + the exec worker refactored and then i'll implement the fast-cgi one ?

@johnduro You can start with FastCGI as soon as the interface is merged. Waiting for me to merge the refactored exec worker probably will make things for you a lot easier since you have some place to look for inspiration. Your decision.

**Comment by johnduro** [comment]
@corvus-ch i think i'll wait for the worker merge as i'm going in holliday soon and i won't be able to do anything while this period

**Pull request merged**
